name = "GameOfLife"
uuid = "34cd62bc-1d08-4a0c-9187-866c57ed52b7"
authors = ["Zuzana Jindrova <jindzuz@fel.cvut.cz> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
